# Generated by Django 3.0.8 on 2021-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarkUsingDCT', '0002_auto_20200426_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qrcodeimg', models.ImageField(upload_to='input/')),
            ],
        ),
    ]
